ParsingError: OtherError changed to store String not &'static str,               conversions from &str to OtherError and Vec<&str> to MultipleErrors Program: parse() now returns a ParsingError instead of Vec<&'static str>